COLUMNS = {

    "Customer": [
        "ID",
        "Customer_OriginalPK",
        "Name",
        "TypeID",
        "TypeName",
        "NationalID",
        "Broker_OriginalPK",
        "IsActive",
    ],

    "Broker": [
        "ID",
        "Broker_OriginalPK",
        "PersianName",
        "EnglishName",
        "CEO",
        "StatusID",
        "StatusName",
        "CodeE",
        "CodeP",
        "NationalID",
    ],

    "Supplier": [
        "ID",
        "Supplier_OriginalPK",
        "Customer_OriginalPK",
        "Customer_Name",
        "Customer_TypeID",
        "Customer_TypeDescription",
        "LevelID",
        "LevelDescription",
        "NationalID",
    ],

    "Ring": [
        "ID",
        "Ring_OriginalPK",
        "Name",
    ],

    "Date": [
        "ID",
        "RealDate",
        "PersianDate",
        "PersianYear",
        "PersianSeason",
        "PersianSeasonName",
        "PersianMonth",
        "PersianMonthName",
        "PersianDayOfMonth",
        "PersianWeekOfYear",
        "PersianDayOfWeek",
        "PersianDayOfWeekName",
    ],

    "Symbol": [
        "ID",
        "Symbol_OriginalPK",
        "TradingSymbol",
        "Commodity_PersianName",
        "Commodity_EnglishName",
        "CommodityMainGroup_PersianName",
        "CommodityGroup_PersianName",
        "CommoditySubGroup_PersianName",
        "Producer_PersianName",
        "Producer_City",
        "Producer_Province",
        "DeliveryPlace_PersianName",
        "Commodity_ShipmentWeight",
    ],

    "Bank": [
        "ID",
        "Name",
        "BranchName",
        "BranchCode",
    ],

    "Carrier": [
        "ID",
        "Name",
        "CEO",
        "Province",
        "City",
        "BrokerName",
    ],

    "Currency": [
        "ID",
        "PersianName",
        "EnglishName",
        "EqualityRate",
    ],

    "ContractKind": [
        "ID",
        "PersianName",
        "EnglishName",
        "KindID",
        "KindDescription",
        "GroupID",
        "GroupDescription",
    ],

    "ContractStatus": [
        "ID",
        "Name",
    ],

    "OfferStatus": [
        "ID",
        "Name",
    ],

    "OfferKind": [
        "ID",
        "Name",
    ],

    "DeliveryPlace": [
        "ID",
        "PersianName",
        "EnglishName",
        "Symbol",
    ],

    "PaymentDelivery": [
        "ID",
        "Name",
        "PaymentKindID",
        "PaymentKindDescription",
        "PaymentCount",
        "DeliveryKindID",
        "DeliveryDescription",
        "DeliveryCount",
    ],

    "ClearingKind": [
        "ID",
        "Name",
    ],

    "GeneralStatus": [
        "ID",
        "Name",
        "Symbol",
    ],

    "OfferItemStatus": [
        "ID",
        "Name",
    ],

    "BuyMethod": [
        "ID",
        "PersianName",
    ],

    "CustomerContract": [
        "ID",
        "CustomerContract_OriginalPK",
        "Quantity",
        "TotalPrice",
        "Electronic",
        "BuyerCustomer_ID",
        "Contract_ID",
        "Date_ID",
        "Ring_ID",
        "Supplier_ID",
        "BuyerBroker_ID",
        "SellerBroker_ID",
        "Symbol_ID",
        "ContractKind_ID",
        "Currency_ID",
        "Bank_ID",
        "Carrier_ID",
        "ClearingKind_ID",
        "ContractStatus_ID",
        "PaymentStatus_ID",
        "TransferStatus_ID",
        "FinantialStatus_ID",
        "BuyBrokerWage",
        "SellBrokerWage",
        "BuyIMEWage",
        "SellIMEWage",
        "PenaltyWage",
    ],

    "Contract": [
        "ID",
        "Contract_OriginalPK",
        "Code",
        "Price",
        "TotalPrice",
        "CustomerContractCount",
        "CustomerContractTotalPrice",
        "HallMatchingQuantity",
        "HallMatchingWeight",
        "HallMatchingPrice",
        "HallMatchingTotalPrice",
        "Date_ID",
        "Ring_ID",
        "Supplier_ID",
        "BuyerBroker_ID",
        "SellerBroker_ID",
        "Symbol_ID",
        "ContractKind_ID",
        "Currency_ID",
        "Offer_ID",
        "OfferKind_ID",
        "ContractStatus_ID",
    ],

    "Offer": [
        "ID",
        "OfferQuantity",
        "OfferPrice",
        "OfferMaxPrice",
        "HallSaleQuantity",
        "HallSaleMinPrice",
        "HallSaleMaxPrice",
        "HallPurchaseQuantity",
        "HallPurchaseMinPrice",
        "HallPurchaseMaxPrice",
        "HallContractCount",
        "HallContractAVGPrice",
        "HallContractTotalQuantity",
        "HallContractTotalPrice",
        "LastContractPrice",
        "Date_ID",
        "Ring_ID",
        "Supplier_ID",
        "Broker_ID",
        "Symbol_ID",
        "ContractKind_ID",
        "Currency_ID",
        "OfferStatus_ID",
        "OfferItemStatus_ID",
        "OfferKind_ID",
        "PaymentDelivery_ID",
        "DeliveryPlace_ID",
        "BuyMethod_ID",
    ],

    "Order": [
        "ID",
        "Order_OriginalPK",
        "OrderStatus",
        "OrderDateTime",
        "OrderLot",
        "BuyOrder_OriginalPK",
        "BuyOrder_Lot",
        "BuyOrder_Price",
        "BuyOrder_Time",
        "Date_ID",
        "OrderBookDate_ID",
        "BuyerCustomer_ID",
        "BuyerBroker_ID",
        "SellerBroker_ID",
        "Supplier_ID",
        "Symbol_ID",
        "Ring_ID",
        "Offer_ID",
    ],
}
